# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

project_name: atomix

before:
  hooks:
    - go mod tidy

builds:
  - id: darwin-amd64
    main: ./cmd/atomix
    binary: atomix
    goos:
      - darwin
    goarch:
      - amd64
    env:
      - CC=o64-clang
      - CXX=o64-clang++
    flags:
      - -mod=readonly
      - -trimpath
    gcflags:
      - all=-N -l
    ldflags:
      - -s -w
      - -X github.com/atomix/cli/pkg/version.shortCommit={{ .ShortCommit }}
      - -X github.com/atomix/cli/pkg/version.commit={{ .FullCommit }}
      - -X github.com/atomix/cli/pkg/version.version=v{{ .Version }}
      - -X github.com/atomix/cli/pkg/version.buildType={{ if .IsSnapshot }}snapshot{{ else }}release{{ end }}
  - id: darwin-arm64
    main: ./cmd/atomix
    binary: atomix
    goos:
      - darwin
    goarch:
      - arm64
    env:
      - CC=oa64-clang
      - CXX=oa64-clang++
    flags:
      - -mod=readonly
      - -trimpath
    gcflags:
      - all=-N -l
    ldflags:
      - -s -w
      - -X github.com/atomix/cli/pkg/version.shortCommit={{ .ShortCommit }}
      - -X github.com/atomix/cli/pkg/version.commit={{ .FullCommit }}
      - -X github.com/atomix/cli/pkg/version.version=v{{ .Version }}
      - -X github.com/atomix/cli/pkg/version.buildType={{ if .IsSnapshot }}snapshot{{ else }}release{{ end }}
  - id: linux-amd64
    main: ./cmd/atomix
    binary: atomix
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CC=gcc
      - CXX=g++
    flags:
      - -mod=readonly
      - -trimpath
    gcflags:
      - all=-N -l
    ldflags:
      - -s -w
      - -X github.com/atomix/cli/pkg/version.shortCommit={{ .ShortCommit }}
      - -X github.com/atomix/cli/pkg/version.commit={{ .FullCommit }}
      - -X github.com/atomix/cli/pkg/version.version=v{{ .Version }}
      - -X github.com/atomix/cli/pkg/version.buildType={{ if .IsSnapshot }}snapshot{{ else }}release{{ end }}
  - id: linux-arm64
    main: ./cmd/atomix
    binary: atomix
    goos:
      - linux
    goarch:
      - arm64
    env:
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
    flags:
      - -mod=readonly
      - -trimpath
    gcflags:
      - all=-N -l
    ldflags:
      - -s -w
      - -X github.com/atomix/cli/pkg/version.shortCommit={{ .ShortCommit }}
      - -X github.com/atomix/cli/pkg/version.commit={{ .FullCommit }}
      - -X github.com/atomix/cli/pkg/version.version=v{{ .Version }}
      - -X github.com/atomix/cli/pkg/version.buildType={{ if .IsSnapshot }}snapshot{{ else }}release{{ end }}
  - id: windows-amd64
    main: ./cmd/atomix
    binary: atomix
    goos:
      - windows
    goarch:
      - amd64
    env:
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    flags:
      - -mod=readonly
      - -trimpath
    gcflags:
      - all=-N -l
    ldflags:
      - -s -w
      - -X github.com/atomix/cli/pkg/version.shortCommit={{ .ShortCommit }}
      - -X github.com/atomix/cli/pkg/version.commit={{ .FullCommit }}
      - -X github.com/atomix/cli/pkg/version.version=v{{ .Version }}
      - -X github.com/atomix/cli/pkg/version.buildType={{ if .IsSnapshot }}snapshot{{ else }}release{{ end }}

dockers:
  - id: atomix-cli
    ids:
      - linux-amd64
    image_templates:
      - "atomix/cli:latest"
      - "{{ if (not .IsSnapshot) }}atomix/cli:{{ .Tag }}{{ end }}"
      - "{{ if (not .IsSnapshot) }}atomix/cli:v{{ .Major }}.{{ .Minor }}{{ end }}"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-{{.ShortCommit}}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'

release:
  github:
    owner: atomix
    name: cli
  prerelease: auto
  draft: true
