# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

project_name: atomix
before:
  hooks:
    - go mod tidy
builds:
  - id: atomix
    main: ./cmd/atomix
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/atomix/cli/internal/atomix/version.version={{ .Version }} -X github.com/atomix/cli/internal/atomix/version.commit={{ .Commit }}
    gcflags:
      - all=-N -l
    targets:
      - linux_amd64
      - darwin_amd64
      - darwin_arm64
dockers:
  - id: atomix-cli
    dockerfile: build/docker/Dockerfile
    ids:
      - atomix
    image_templates:
      - atomix/cli:latest
      - atomix/cli:{{ .Tag }}
      - atomix/cli:v{{ .Major }}.{{ .Minor }}
    extra_files:
      - build/output/atomix_linux_amd64
snapshot:
  name_template: "{{ incpatch .Version }}-dev"
changelog:
  sort: asc
