# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

project_name: atomix
before:
  hooks:
    - go mod tidy
builds:
  - id: atomix
    hooks:
      pre:
        - docker run -i -v {{ abs "." }}:/build atomix/build:1.18-{{ .Os }}-{{ .Arch }} bin --version={{ .Version }} --commit={{ .Commit }} -o build/output/atomix_{{ .Os }}_{{ .Arch }} ./cmd/atomix
    builder: prebuilt
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    targets:
      - linux_amd64
      - darwin_amd64
      - darwin_arm64
    prebuilt:
      path: build/output/atomix_{{ .Os }}_{{ .Arch }}
dockers:
  - id: atomix-cli
    dockerfile: build/docker/Dockerfile
    ids:
      - atomix
    image_templates:
      - atomix/cli:latest
      - atomix/cli:{{ .Tag }}
      - atomix/cli:v{{ .Major }}.{{ .Minor }}
    extra_files:
      - build/output/atomix_linux_amd64
snapshot:
  name_template: "{{ incpatch .Version }}-dev"
changelog:
  sort: asc
