# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

project_name: atomix

before:
  hooks:
    - go mod tidy

builds:
  - id: darwin-amd64
    main: ./cmd/atomix
    binary: atomix
    goos:
      - darwin
    goarch:
      - amd64
    env:
      - CC=o64-clang
      - CXX=o64-clang++
    flags:
      - -mod=readonly
      - -trimpath
    gcflags:
      - all=-N -l
    ldflags:
      - -s -w -X github.com/atomix/cli/pkg/atomix/version.version={{ .Version }} -X github.com/atomix/cli/pkg/atomix/version.commit={{ .Commit }}
  - id: darwin-arm64
    main: ./cmd/atomix
    binary: atomix
    goos:
      - darwin
    goarch:
      - arm64
    env:
      - CC=oa64-clang
      - CXX=oa64-clang++
    flags:
      - -mod=readonly
      - -trimpath
    gcflags:
      - all=-N -l
    ldflags:
      - -s -w -X github.com/atomix/cli/pkg/atomix/version.version={{ .Version }} -X github.com/atomix/cli/pkg/atomix/version.commit={{ .Commit }}
  - id: linux-amd64
    main: ./cmd/atomix
    binary: atomix
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CC=gcc
      - CXX=g++
    flags:
      - -mod=readonly
      - -trimpath
    gcflags:
      - all=-N -l
    ldflags:
      - -s -w -X github.com/atomix/cli/pkg/atomix/version.version={{ .Version }} -X github.com/atomix/cli/pkg/atomix/version.commit={{ .Commit }}
  - id: linux-arm64
    main: ./cmd/atomix
    binary: atomix
    goos:
      - linux
    goarch:
      - arm64
    env:
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
    flags:
      - -mod=readonly
      - -trimpath
    gcflags:
      - all=-N -l
    ldflags:
      - -s -w -X github.com/atomix/cli/pkg/atomix/version.version={{ .Version }} -X github.com/atomix/cli/pkg/atomix/version.commit={{ .Commit }}
  - id: windows-amd64
    main: ./cmd/atomix
    binary: atomix
    goos:
      - windows
    goarch:
      - amd64
    env:
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    flags:
      - -mod=readonly
      - -trimpath
    gcflags:
      - all=-N -l
    ldflags:
      - -s -w -X github.com/atomix/cli/pkg/atomix/version.version={{ .Version }} -X github.com/atomix/cli/pkg/atomix/version.commit={{ .Commit }}

dockers:
  - id: atomix-cli
    dockerfile: build/docker/Dockerfile
    ids:
      - linux-amd64
    image_templates:
      - atomix/cli:latest
      - atomix/cli:{{ .Tag }}
      - atomix/cli:v{{ .Major }}.{{ .Minor }}

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-dev"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'

release:
  github:
    owner: atomix
    name: cli
  prerelease: auto
  draft: true
